### PR TITLE
Refactor: Character and World use es6 class instead of prototype

### PR DESCRIPTION
**Pull request by Sy1v4in**
To finish the es6 refactor ;-)

### CODE REVIEW

**Comment by ldez** [comment]
I do the same in #4  :wink: 
I also add Gulp and ESLint with rules for React.

**Comment by FranckErnewein** [comment]
If you don't install mocha globally you can use it as a binary ??
`mocha test/*.js` will work ?

**Comment by Sy1v4in** [comment]
Yes, it works via `npm` which add `node_modules` in its path when it launches scripts.
And if you want to launch it manually, you can use `node_modules/.bin/mocha test/*.js`

**Comment by FranckErnewein** [comment]
so we need change the `npm test` cmd, right ?

**Comment by ldez** [comment]
no need, because libs in `node_module` can be call directly.
But you need to add `mocha` in `devDependencies`.
For example you can define `start: grunt`  within `package.json` see #4.

**Comment by FranckErnewein** [comment]
merged !

**Pull request closed without merging**
